elanel_web/urls.py
from unicodedata import name
from django import urls
from django.contrib import admin
from django.urls import path, include
# from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from .views import IndexView2, SobreNosotros,Contactanos,page_error, Privicidad

handler404 = page_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",IndexView2.as_view(), name = "index"),
    path("nosotros/",SobreNosotros.as_view(), name = "nosotros"),
    path("contactanos/",Contactanos.as_view(), name = "contactanos"),
    path("politicas_de_privacidad/",Privicidad.as_view(), name = "privacidad"),
    path("notfound/", page_error,name="error"),
    path("m/", include("market.urls", namespace="market")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from market.views import  TrabajaConNosotros, CategoriaMotos,DetalleElec,DetalleSolucion,CategoriaElectrodemesticos,CategoriaSolucionesDinerarias, CategoriaBeneficiosCliente, Categorias,DetalleMoto
app_name="market"

urlpatterns = [
    path("categorias/",Categorias.as_view(),name="categorias"),

    path("categorias/motos/",CategoriaMotos.as_view(),name="motos"),
    path("categorias/motos/<slug:slug>/", DetalleMoto.as_view(),name="moto"),
    path("categorias/motos/", CategoriaMotos.as_view(), name="clear"),


    path("categorias/elec/",CategoriaElectrodemesticos.as_view(), name="electrodomesticos"),
    path("categorias/elec/<slug:slug>/", DetalleElec.as_view(),name="electrodomestico"),
    path("categorias/elec/", CategoriaElectrodemesticos.as_view(),name="clear_electrodomesticos"),

    path("categorias/beneficios/", CategoriaBeneficiosCliente.as_view(), name="beneficios"),
    

    path("categorias/soluciones_dinerarias/", CategoriaSolucionesDinerarias.as_view(),name="soluciones_dinerarias"),
    path("categorias/soluciones_dinerarias/<int:pk>/", DetalleSolucion.as_view(),name="solucione_detail"),
    path("categorias/soluciones_dinerarias/", CategoriaSolucionesDinerarias.as_view(),name="clear_soluciones"),

    path("trabaja_con_nosotros/", TrabajaConNosotros.as_view(),name="trabaja"),
]

market/forms.py
from market.models import Personal,BeneficioParaCliente,Cliente
from django import forms
class FormPersonal(forms.ModelForm):
    class Meta:
        model = Personal
        fields =[
            'nombre_completo',
            'email',
            'num_telefono',
            'cv',
        ]

class FormBeneficios(forms.ModelForm):
    class Meta:
        model = BeneficioParaCliente
        fields =[
            'nombre_completo',
            'email',
            'num_telefono',
            'servicio',
            'producto',
            'monto'
        ]
class FormDinero(forms.ModelForm):
    class Meta:
        model = Cliente
        fields =[
            'nombre_completo',
            'email',
            'provincia',
            'num_telefono',
            'objetivo',
        ]
        
class FormMotos(forms.ModelForm):
    class Meta:
        model = Cliente
        fields =[
            'nombre_completo',
            'email',
            'provincia',
            'num_telefono',
            'objetivo',
        ]
class FormElec(forms.ModelForm):
    class Meta:
        model = Cliente
        fields =[
            'nombre_completo',
            'email',
            'provincia',
            'num_telefono',
            'objetivo',
        ]

market/views.py
import json
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views.generic import View
from django.views import generic
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from market.models import Electrodomestico,Cliente ,ImagenMoto,ImagenElectrodomestico, Post, Moto, Personal,BeneficioParaCliente,SolucionDineraria
from .forms import FormPersonal,FormBeneficios,FormDinero,FormMotos,FormElec
import os


   

class Categorias(generic.ListView):
    template_name = "templates_categorias/categorias.html"
    
    def get_queryset(self):
        return None

def is_valid_query(param):
        return param != "" and param is not None

class CategoriaMotos(generic.ListView):
    template_name = "templates_categorias/categorias_motos.html"
    model = Moto
    context_object_name ="motos"

    def get_queryset(self):
        qs = super().get_queryset()
        marca = self.request.GET.get("marca")
        status = self.request.GET.get("status")
        minimo = self.request.GET.get("minimo")
        maximo = self.request.GET.get("maximo")
        # status = self.request.GET.get("status")
        if is_valid_query(marca):
            qs = qs.filter(marca = marca)
        if is_valid_query(status):
            qs = qs.filter(usado = status)
        if is_valid_query(minimo):
            qs = qs.filter(precio__gte = minimo)
        if is_valid_query(maximo):
            qs = qs.filter(precio__lte = maximo)
            
        return qs
    

class DetalleMoto(generic.DetailView):
    model = Moto
    template_name = "templates_categorias/detalle_moto.html"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        context ={}
        context["moto_images"] = ImagenMoto.objects.filter(producto = self.object)
        context["object"] = self.object
        try:
            model = Moto.objects.filter(slug = self.object.slug)
            archivo =os.path.split(str(model[0].ficha_tecnica))[1]
            context["ficha_tecnica"] = archivo
        except ValueError:
            print("No existe ficha tecnica")

        return render(request,self.template_name,context)
    
    def post(self,request,*args, **kwargs):
        self.object = self.get_object()
        form = FormMotos()
        if request.method == "POST":
            form = FormMotos(request.POST)
            if form.is_valid():
                print("es valido")
                form_moto = Cliente()
                form_moto.nombre_completo = form.cleaned_data['nombre_completo']
                form_moto.email = form.cleaned_data['email']
                form_moto.num_telefono = form.cleaned_data['num_telefono']
                form_moto.provincia = form.cleaned_data['provincia']
                form_moto.objetivo = form.cleaned_data['objetivo']
                form_moto.save()
                
            else:
                message_error = {"message": "No valido"}
                data = json.dumps(message_error)
                return HttpResponse(data,"application/json")

        return redirect('market:moto',self.object.slug)

    

        

class CategoriaElectrodemesticos(generic.ListView):
    model = Electrodomestico
    template_name = "templates_categorias/categorias_electrodomesticos.html"
    context_object_name ="electrodomesticos"

    def get_queryset(self):
        qs = super().get_queryset()
        cuota = self.request.GET.get("cuota")
        combo = self.request.GET.get("combo")
        minimo = self.request.GET.get("minimo")
        maximo = self.request.GET.get("maximo")
        if is_valid_query(cuota):
            qs = qs.filter(cuota = cuota)
        if is_valid_query(combo):
            qs = qs.filter(combo = combo)
        if is_valid_query(minimo):
            qs = qs.filter(precio__gte = minimo)
        if is_valid_query(maximo):
            qs = qs.filter(precio__lte = maximo)
            
        return qs



class DetalleElec(generic.DetailView):
    model = Electrodomestico
    template_name = "templates_categorias/detalle_electrodomesticos.html"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        context ={}
        context["electrodomesticos_images"] = ImagenElectrodomestico.objects.filter(producto = self.object)
        context["object"] = self.object
        try:
            model = Moto.objects.filter(slug = self.object.slug)
            archivo =os.path.split(str(model[0].ficha_tecnica))[1]
            context["ficha_tecnica"] = archivo
        except:
            print("No existe ficha tecnica")

        return render(request,self.template_name,context)

    def post(self,request,*args, **kwargs):
        self.object = self.get_object()
        form = FormElec()
        if request.method == "POST":
            form = FormElec(request.POST)
            if form.is_valid():
                print("es valido")
                form_elec = Cliente()
                form_elec.nombre_completo = form.cleaned_data['nombre_completo']
                form_elec.email = form.cleaned_data['email']
                form_elec.num_telefono = form.cleaned_data['num_telefono']
                form_elec.provincia = form.cleaned_data['provincia']
                form_elec.objetivo = form.cleaned_data['objetivo']
                form_elec.save()
            else:
                message_error = {"message": "No valido"}
                data = json.dumps(message_error)
                return HttpResponse(data,"application/json")

        return redirect('market:electrodomestico',self.object.slug)


class CategoriaSolucionesDinerarias(generic.ListView):
    template_name = "templates_categorias/categorias_soluciones_dinerarias.html"
    model = SolucionDineraria
    context_object_name ="dineros"

    def get_queryset(self):
        qs = super().get_queryset()
        cuota = self.request.GET.get("cuota")
        if is_valid_query(cuota):
            qs = qs.filter(cuota = cuota)
        return qs
    

class DetalleSolucion(generic.DetailView):
    model = SolucionDineraria
    template_name = "templates_categorias/detalle_soluciones.html"

    
            
    def post(self,request,*args, **kwargs):
        self.object = self.get_object()
        form = FormDinero()
        if request.method == "POST":
            print("Entre POST")
            form = FormDinero(request.POST)
            if form.is_valid():
                print("es valido")
                solu_dine = Cliente()
                solu_dine.nombre_completo = form.cleaned_data['nombre_completo']
                solu_dine.email = form.cleaned_data['email']
                solu_dine.num_telefono = form.cleaned_data['num_telefono']
                solu_dine.provincia = form.cleaned_data['provincia']
                solu_dine.objetivo = form.cleaned_data['objetivo']
                solu_dine.save()
            else:
                message_error = {"message": "No valido"}
                data = json.dumps(message_error)
                return HttpResponse(data,"application/json")
        return redirect('market:solucione_detail',self.object.id)

    

    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        context ={}
        
        context["object"] = self.object

        return render(request,self.template_name,context)


class CategoriaBeneficiosCliente(generic.ListView):
    template_name = "templates_categorias/categorias_beneficios_cliente.html"

    def post(self,request,*args, **kwargs):
        form = FormBeneficios()
        if request.method == "POST":
            print("Entre POST")
            form = FormBeneficios(request.POST)
            if form.is_valid():
                print("es valido")
                beneficio = BeneficioParaCliente()
                beneficio.nombre_completo = form.cleaned_data['nombre_completo']
                beneficio.email = form.cleaned_data['email']
                beneficio.num_telefono = form.cleaned_data['num_telefono']
                beneficio.servicio = form.cleaned_data['servicio']
                beneficio.producto = form.cleaned_data['producto']
                beneficio.monto = form.cleaned_data['monto']
                beneficio.save()
            else:
                message_error = {"message": "No valido"}
                data = json.dumps(message_error)
                return HttpResponse(data,"application/json")

        return(render(request,self.template_name))

    def get(self, request, *args, **kwargs):
        context = {}
        productos_basico =  list(Moto.objects.filter(servicio="Basico")) + list(Electrodomestico.objects.filter(servicio="Basico"))
        productos_estandar = list(Moto.objects.filter(servicio="Estandar"))+ list(Electrodomestico.objects.filter(servicio="Estandar"))
        productos_premium = list(Moto.objects.filter(servicio="Premium"))+ list(Electrodomestico.objects.filter(servicio="Premium"))
        
        all_products = productos_estandar + productos_premium + productos_basico


        context["productos_basico"]  = productos_basico
        context["productos_estandar"]  = productos_estandar
        context["productos_premium"]  = productos_premium

        
        products_list =[]
        for product in all_products:
            data_product = {}
            data_product['nombre'] = product.nombre
            data_product['servicio'] = product.servicio
            if product.monto_servicio_por_couta == None:
                data_product['monto_mensual'] = 0
                data_product['monto_total'] = 0
            else:
                data_product['monto_mensual'] = product.monto_servicio_por_couta
                data_product['monto_total'] = product.monto_servicio_por_couta*12
            products_list.append(data_product)
        data = json.dumps(products_list)

market/templates/templates_categorias/categorias.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/categorias.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <title>Elanel Servicios y Soluciones</title>
    <link
      rel="shortcut icon"
      href="{% static 'images/fwd/icon_page4.png' %}"
    />
  </head>
  <body>
    {% include 'nav.html' %}

    <section class="categorias">
      <article class="motos">
        <figure>
          <img src="{% static 'images/icons/moto_icon.png' %}" alt="" />
        </figure>
        <a href="{% url 'market:motos' %}"><h1>Motos</h1></a>
        <ul>
          <li>
            <a href="" id="moto_yamaha"><h2>Yamaha</h2></a>
          </li>
          <li>
            <a href="" id="moto_honda"><h2>Honda</h2></a>
          </li>
          <li>
            <a href="" id="moto_motomel"><h2>Motomel</h2></a>
          </li>
          <li>
            <a href="" id="moto_rouser"><h2>Rouser</h2></a>
          </li>
          <li>
            <a href="{% url 'market:motos' %}"><h2>Ver más...</h2> </a>
          </li>
        </ul>
      </article>

      <article class="electrodomesticos">
        <figure>
          <img
            src="{% static 'images/icons/icon_electrodo_relleno.png' %}"
            alt=""
          />
        </figure>
        <a href="{% url 'market:electrodomesticos' %}"
          ><h1>Electrodomesticos</h1></a
        >
        <ul>
          <li>
            <a href="" id="combo_cocina"><h2>Combo cocina</h2></a>
          </li>
          <li>
            <a href="" id="combo_gamer"><h2>Combo gamer</h2></a>
          </li>
          <li>
            <a href="" id="combo_musica"><h2>Combo música</h2></a>
          </li>
          <li>
            <a href="" id="combo_tv"><h2>Combo TV</h2></a>
          </li>
          <li>
            <a href="{% url 'market:motos' %}"><h2>Ver más...</h2> </a>
          </li>
        </ul>
      </article>

      <article class="soluciones_dinerarias">
        <figure>
          <img
            src="{% static 'images/icons/icon_solu_dineraria.png' %}"
            alt=""
          />
        </figure>
        <a href="{% url 'market:soluciones_dinerarias' %}"
          ><h1>Soluciones Dinerarias</h1></a
        >
      </article>

    </section>
    <script src="{% static 'js/header.js' %}"></script>
    <script src="{% static 'js/menu_hamburguer.js' %}"></script>
    <script src="{% static 'js/redirect_alternative.js' %}"></script>
  </body>
</html>

market/templates/templates_categorias/categorias_electrodomesticos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/categorias_details.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/categorias_electrodomesticos.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/media_querys/categorias_motos.css' %}"
    />
    <title>Elanel Servicios y Soluciones</title>
    <link
      rel="shortcut icon"
      href="{% static 'images/fwd/icon_page4.png' %}"
    />
  </head>
  <body>
    {% include 'nav.html' %}

    <div class="wrapper_catalogo_aside">
      <aside class="filters_container">
        <form action="" method="get">
          <h1>Combos</h1>
          <div class="combos">
            <input type="radio" name="combo" id="cocina" value="cocina" />
            <label for="cocina">
              <h3>Combos cocina</h3>
            </label>

            <input type="radio" name="combo" id="tecnologia" value="tecnologia" />
            <label for="tecnologia">
              <h3>Combos tecnologia</h3>
            </label>

            <input type="radio" name="combo" id="dormitorio" value="dormitorio" />
            <label for="dormitorio">
              <h3>Combos dormitorio</h3>
            </label>

            <input type="radio" name="combo" id="living" value="living" />
            <label for="living">
              <h3>Combos living</h3>
            </label>

            <input type="radio" name="combo" id="hogar" value="hogar" />
            <label for="hogar">
              <h3>Combos hogar</h3>
            </label>
          </div>

          <!-- <h1>Coutas</h1>
          <div class="cuotas">
            <input type="radio" name="cuota" id="venticuatro" value="24" />
            <label for="venticuatro">
              <h3>24</h3>
            </label>

            <input type="radio" name="cuota" id="treinta" value="30" />
            <label for="treinta">
              <h3>30</h3>
            </label>

            <input type="radio" name="cuota" id="cuarentaocho" value="48" />
            <label for="cuarentaocho">
              <h3>48</h3>
            </label>

            <input type="radio" name="cuota" id="sesenta" value="60" />
            <label for="sesenta">
              <h3>60</h3>
            </label>
          </div> -->

          <h1>Precio</h1>
          <div class="precio">
            <input
              type="text"
              pattern="[0-9]*"
              name="minimo"
              id="minimo"
              placeholder="Minimo"
            />
            <input
              type="text"
              pattern="[0-9]*"
              name="Maximo"
              id="maximo"
              placeholder="Maximo"
            />
          </div>
          <button type="submit" id="button_filter">Buscar</button>
          <a id="clear" href="{%  url 'market:clear_electrodomesticos' %}"
            >Limpiar filtros</a
          >
        </form>
      </aside>
      <button type="button" id="filter_button">Filtrar</button>
      <section class="catalogo">
        {% if electrodomesticos.count != 0 %} 
          {% for electrodomestico in electrodomesticos %}
          <a href="{% url 'market:electrodomestico' electrodomestico.slug %}">
            <article>
              <img src="{{electrodomestico.imagen_portada.url}}" alt="" />
              <div>
                <h2>{{electrodomestico.nombre}}</h2>
                <h3>Consultar precio</h3>
              </div>
            </article>
          </a>
          {% endfor %} 
        {% elif electrodomesticos.count == 0 %}
        <div class="not_found">
          <figure>
            <img src="{% static 'images/icons/nothing-found.png' %}" alt="" />
          </figure>
          <h1>¡Ups! Al parecer no se encuentran productos disponibles</h1>
        </div>
        {% endif %}
      </section>
    </div>
  </body>
  <script src="{% static 'js/header.js' %}"></script>
  <script src="{% static 'js/filter_button.js' %}"></script>
  <script src="{% static 'js/menu_hamburguer.js' %}"></script>
  <script src="{% static 'js/clear_filter_elec.js' %}"></script>
</html>

market/templates/templates_categorias/categorias_motos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/categorias_details.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/media_querys/categorias_motos.css' %}"
    />
    <title>Elanel Servicios y Soluciones</title>
    <link
      rel="shortcut icon"
      href="{% static 'images/fwd/icon_page4.png' %}"
    />
  </head>
  <body>
    {% include 'nav.html' %}

    <div class="wrapper_catalogo_aside">
      <aside class="filters_container">
        <form action="" method="GET">
          <h1>Marcas</h1>
          <div class="marcas">
            <input type="radio" name="marca" id="yamaha" value="yamaha" />
            <label for="yamaha">
              <h3>Yamaha</h3>
            </label>

            <input type="radio" name="marca" id="honda" value="honda" />
            <label for="honda">
              <h3>Honda</h3>
            </label>

            <input type="radio" name="marca" id="motomel" value="motomel" />
            <label for="motomel">
              <h3>Motomel</h3>
            </label>

            <input type="radio" name="marca" id="rouser" value="rouser" />
            <label for="rouser">
              <h3>Rouser</h3>
            </label>

            <input type="radio" name="marca" id="corven" value="corven" />
            <label for="corven">
              <h3>Corven</h3>
            </label>

            <input type="radio" name="marca" id="zanella" value="zanella" />
            <label for="zanella">
              <h3>Zanella</h3>
            </label>
          </div>

          <h1>Condición</h1>
          <div class="estado">
            <input type="radio" name="status" id="nuevo" value="False" />
            <label for="nuevo"><h3>Nuevo</h3></label>

            <input type="radio" name="status" id="usado" value="True" />
            <label for="usado"><h3>Usado</h3></label>
          </div>

          <h1>Precio</h1>
          <div class="precio">
            <input
              type="text"
              pattern="[0-9]*"
              name="minimo"
              id="minimo"
              placeholder="Minimo"
            />
            <input
              type="text"
              pattern="[0-9]*"
              name="maximo"
              id="maximo"
              placeholder="Maximo"
            />
          </div>
          <button type="submit" id="button_filter">Buscar</button>
        </form>
        <a id="clear" href="{%  url 'market:clear' %}">Limpiar filtros</a>
      </aside>
      <button type="button" id="filter_button">Filtrar</button>

      <section class="catalogo">
        {% if motos.count != 0 %} {% for moto in motos %}
        <a href="{% url 'market:moto' moto.slug %}">
          <article>
            <img src="{{moto.imagen_portada.url}}" alt="" />
            <div>
              <h2>{{moto.nombre}}</h2>
              <h3>Consultar precio</h3>
            </div>
          </article>
        </a>
        {% endfor %} {% elif motos.count == 0 %}
        <div class="not_found">
          <figure>
            <img src="{% static 'images/icons/nothing-found.png' %}" alt="" />
          </figure>
          <h1>¡Ups! Al parecer no se encuentran productos disponibles</h1>
        </div>
        {% endif %}
      </section>
    </div>
  </body>
  <script src="{% static 'js/header.js' %}"></script>
  <script src="{% static 'js/filter_button.js' %}"></script>
  <script src="{% static 'js/menu_hamburguer.js' %}"></script>
  <script src="{% static 'js/clear_filters_motos.js' %}"></script>
</html>

market/templates/templates_categorias/categorias_soluciones_dinerarias.html
{% load static %}
{% load humanize %}
{% load i18n %}
{% load l10n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/categorias_details.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/categorias_soluciones.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/media_querys/categorias_motos.css' %}"
    />

    <title>Elanel Servicios y Soluciones</title>
    <link
      rel="shortcut icon"
      href="{% static 'images/fwd/icon_page4.png' %}"
    />
  </head>
  <body>
    {% include 'nav.html' %}

    <div class="wrapper_catalogo_aside">
      <!-- <aside class="filters_container">
        <form action="" method="get">
          <h1>Coutas</h1>
          <div class="cuotas">
            <input type="radio" name="cuota" id="venticuatro" value="24" />
            <label for="venticuatro">
              <h3>24</h3>
            </label>

            <input type="radio" name="cuota" id="treinta" value="30" />
            <label for="treinta">
              <h3>30</h3>
            </label>

            <input type="radio" name="cuota" id="cuarentaocho" value="48" />
            <label for="cuarentaocho">
              <h3>48</h3>
            </label>

            <input type="radio" name="cuota" id="sesenta" value="60" />
            <label for="sesenta">
              <h3>60</h3>
            </label>
          </div>
          <button type="submit" id="button_filter">Buscar</button>
        </form>
        <a id="clear" href="{%  url 'market:clear_soluciones' %}"
          >Limpiar filtros</a
        >
      </aside> -->
      <!-- <button type="button" id="filter_button">Filtrar</button> -->
      <section class="catalogo">
        {% if dineros.count != 0 %} 
          {% for monto in dineros %}
            <a href="{% url 'market:solucione_detail' monto.id %}">
              <article>
                <img src="{% static 'images/icons/dollar.svg' %}" alt="" />
                <div>
                  <h2>${{monto.monto|floatformat:0|intcomma}}</h2>
                  <h3>{{monto.cuota}} Cuotas</h3>
                </div>
              </article>
            </a>
          {% endfor %} 
        {% elif dineros.count == 0 %}
        <div class="not_found">
          <figure>
            <img src="{% static 'images/icons/nothing-found.png' %}" alt="" />
          </figure>
          <h1>¡Ups! Al parecer no se encuentran productos disponibles</h1>
        </div>
        {% endif %}
      </section>
    </div>

    
  </body>
  <script src="{% static 'js/header.js' %}"></script>
  <script src="{% static 'js/filter_button.js' %}"></script>
  <script src="{% static 'js/menu_hamburguer.js' %}"></script>
  <script src="{% static 'js/clear_filter_dinero.js' %}"></script>
</html>