elanel_web/urls.py
from unicodedata import name
from django import urls
from django.contrib import admin
from django.urls import path, include
# from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from .views import IndexView2, SobreNosotros,Contactanos,page_error, Privicidad

handler404 = page_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",IndexView2.as_view(), name = "index"),
    path("nosotros/",SobreNosotros.as_view(), name = "nosotros"),
    path("contactanos/",Contactanos.as_view(), name = "contactanos"),
    path("politicas_de_privacidad/",Privicidad.as_view(), name = "privacidad"),
    path("notfound/", page_error,name="error"),
    path("m/", include("market.urls", namespace="market")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from market.views import  TrabajaConNosotros, CategoriaMotos,DetalleElec,DetalleSolucion,CategoriaElectrodemesticos,CategoriaSolucionesDinerarias, CategoriaBeneficiosCliente, Categorias,DetalleMoto
app_name="market"

urlpatterns = [
    path("categorias/",Categorias.as_view(),name="categorias"),

    path("categorias/motos/",CategoriaMotos.as_view(),name="motos"),
    path("categorias/motos/<slug:slug>/", DetalleMoto.as_view(),name="moto"),
    path("categorias/motos/", CategoriaMotos.as_view(), name="clear"),


    path("categorias/elec/",CategoriaElectrodemesticos.as_view(), name="electrodomesticos"),
    path("categorias/elec/<slug:slug>/", DetalleElec.as_view(),name="electrodomestico"),
    path("categorias/elec/", CategoriaElectrodemesticos.as_view(),name="clear_electrodomesticos"),

    path("categorias/beneficios/", CategoriaBeneficiosCliente.as_view(), name="beneficios"),
    

    path("categorias/soluciones_dinerarias/", CategoriaSolucionesDinerarias.as_view(),name="soluciones_dinerarias"),
    path("categorias/soluciones_dinerarias/<int:pk>/", DetalleSolucion.as_view(),name="solucione_detail"),
    path("categorias/soluciones_dinerarias/", CategoriaSolucionesDinerarias.as_view(),name="clear_soluciones"),

    path("trabaja_con_nosotros/", TrabajaConNosotros.as_view(),name="trabaja"),
]

templates/contactanos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/contactanos.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/media_querys/contactanos.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/footer.css' %}" />
    <title>Elanel Servicios y Soluciones</title>
    <link
      rel="shortcut icon"
      href="{% static 'images/fwd/icon_page4.png' %}"
    />
  </head>
  <body>
    {% include 'nav.html' %}

    <section class="wrapper_comunicate">
      <article class="contactanos">
        <h1>Comunicate</h1>
        <div class="locales">

          <div id="resistencia" class="local">
            <div class="text_provincia_container">
              <h1>Casa Central - Resistencia, Chaco</h1>
            </div>
            <div class="secciones">
              <ol>
                <li class="sector">
                  <h3>Administracion</h3>
                  <div class="sector_info">
                    <h5 class="number_phone">362 517-0890</h5>
                    <h5 class="correo">atencionaclientes@elanelsys.com</h5>
                  </div>
                </li>
                <li class="sector">
                  <h3>Ventas</h3>
                  <div class="sector_info">
                    <h5 class="correo">ventas@elanelsys.com</h5>
                  </div>
                </li>
                <li class="sector">
                  <h3>Cobranzas</h3>
                  <div class="sector_info">
                    <h5 class="correo">cobranzas@elanelsys.com</h5>
                  </div>
                </li>
              </ol>
            </div>
          </div>

          <div id="corrientes_capital" class="local">
            <div class="text_provincia_container">
              <h1>Corrientes Capital</h1>
            </div>
            <div class="secciones">
              <ol>
                <li class="sector">
                  <h3>Telefono:</h3>
                  <div class="sector_info">
                    <h5 class="number_phone">379 516-1905</h5>
                  </div>
                </li>
                <li class="sector">
                  <h3>Correo electronico</h3>
                  <div class="sector_info">
                    <h5 class="correo">agenciacorrientes@elanelsys.com</h5>
                  </div>
                </li>
              </ol>
            </div>
          </div>

          <div id="saenz_penia" class="local">
            <div class="text_provincia_container">
              <h1>Saenz Peña, Chaco</h1>
            </div>
            <div class="secciones">
              <ol>
                <li class="sector">
                  <h3>Telefono:</h3>
                  <div class="sector_info">
                    <h5 class="number_phone">364 491-4025</h5>
                  </div>
                </li>
                <li class="sector">
                  <h3>Correo electronico</h3>
                  <div class="sector_info">
                    <h5 class="correo">agenciasaenzpenia@elanelsys.com</h5>
                  </div>
                </li>
              </ol>
            </div>
          </div>

          <div id="posadas" class="local">
            <div class="text_provincia_container">
              <h1>Posadas, Misiones</h1>
            </div>
            <div class="secciones">
              <ol>
                <li class="sector">
                  <h3>Telefono:</h3>
                  <div class="sector_info">
                    <h5 class="number_phone">3765 10-4719</h5>
                  </div>
                </li>
                <li class="sector">
                  <h3>Correo electronico</h3>
                  <div class="sector_info">
                    <h5 class="correo">agenciaposadas@elanelsys.com</h5>
                  </div>
                </li>
              </ol>
            </div>
          </div>

          <div id="goya" class="local">
            <div class="text_provincia_container">
              <h1>Goya, Corrientes</h1>
            </div>
            <div class="secciones">
              <ol>
                <li class="sector">
                  <h3>Correo electronico</h3>
                  <div class="sector_info">
                    <h5 class="correo">agenciagoya@elanelsys.com</h5>
                  </div>
                </li>
              </ol>
            </div>
          </div>

        </div>
  
      </article>
     {% comment %} <article class="preguntas_frecuentes">
        <h1>Preguntas Frecuentes</h1>
        <ul>
          <li class="question">
            <h2>Pregunta 1</h2>
            <p class="texts">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam
              debitis quae quidem voluptatibus ut dolore molestiae atque cumque,
              iste deleniti aliquid quasi dignissimos totam facilis voluptate
              reiciatibus ut dolore molestiae atque cumque, iste deleniti
              aliquid quasi dignissimos totam facilis voluptate reiciendis. Nam,
              iste odio.. sicing elit. Quisquam debitis quae quidem voluptatibu.
            </p>
          </li>
          <li class="question">
            <h2>Pregunta 2</h2>
            <div class="texts">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Quisquam debitis quae quidem voluptatibus ut dolore molestiae
                atque cumque, iste deleniti aliquid quasi dignissimos totam
                facilis voluptate reiciendis. Nam, iste odio..
              </p>
            </div>
          </li>
          <li class="question">
            <h2>Pregunta 3</h2>
            <div class="texts">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Quisquam debitis quae quidem voluptatibus ut dolore molestiae
                atque cumque, iste deleniti aliquid quasi dignissimos totam
                facilis voluptate reiciendis. Nam, iste odio..
              </p>
            </div>
          </li>
          <li class="question">
            <h2>Pregunta 4</h2>
            <div class="texts">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Quisquam debitis quae quidem voluptatibus ut dolore molestiae
                atque cumque, iste deleniti aliquid quasi dignissimos totam
                facilis voluptate reiciendis. Nam, iste odio..
              </p>
            </div>
          </li>
        </ul>
      </article>{% endcomment %}
    </section>
    <script src="{% static 'js/header.js' %}"></script>
    <script src="{% static 'js/preguntas_frecuentes.js' %}"></script>
    <script src="{% static 'js/menu_hamburguer.js' %}"></script>  
  </body>
</html>

templates/footer.html
{% load static %}
<footer>

        <div class="footer__encuentranos">
          <h3>Encuentranos</h3>
          <ul>
            <li class="footer__direccion"> 
              <p><strong>Corrientes:</strong> 9 de Julio 1687 Local 2</p>
              <p><strong>Resistencia:</strong> Obligado 841 Local B</p>
            </li>
            <li class="footer__social-media"> 
              <a href="https://m.facebook.com/elanelsys" target=”_blank”>
                <img src="{% static 'images/icons/social_face.png' %}" alt="">
              </a>
              <a href="https://www.instagram.com/elanel.servicios/?hl=es-la" target=”_blank”>
                <img src="{% static 'images/icons/social_insta.png' %}" alt="">
              </a>
              <a href="https://www.tiktok.com/@elaneloficial" target=”_blank”>
                <img src="{% static 'images/icons/tiktok_icon.svg' %}" alt="">
              </a>
              <a href="whatsapp.com" target=”_blank”>
                <img src="{% static 'images/icons/social_whatsapp.png' %}" alt="">
              </a>
            </li>
          </ul>
        </div>

        <div class="footer__categorias">
          <ul>
            <li class="footer__motos"> 
              <a href="{% url 'market:motos' %}">Motos</a>
            </li>
            <li class="footer__soluciones-dinerarias"> 
              <a href="{% url 'market:soluciones_dinerarias' %}">Soluciones Dinerarias</a>
            </li>
            <li class="footer__electrodomesticos"> 
              <a href="{% url 'market:electrodomesticos' %}">Electrodomesticos</a>
            </li>
            <li class="footer__beneficios-para-cliente"> 
              <a href="{% url 'market:beneficios' %}">Beneficios para cliente</a>
            </li>
          </ul>
        </div>

        <div class="footer__quienes-somos">
          <h3>Quienes Somos</h3>
          <ul>
            <li class="footer__mision"> 
              <a href="{% url 'nosotros' %}">Mision</a>
            </li>
            <li class="footer__vision"> 
              <a href="{% url 'nosotros' %}">Vision</a>
            </li>
            <li class="footer__vision"> 
              <a href="{% url 'privacidad' %}">Politicas de privacidad</a>
            </li>
          </ul>
        </div>

        <div class="footer__contactanos">
          <h3>Contactanos</h3>
          <ul>
            <li class="footer__contactanos-item">
              <h5>Resistencia, Chaco</h5>
              <div class="info">
                <div class="tel">
                  <img src="{% static 'images/icons/social_tel.png' %}" alt="">
                  <p>362 524-5484</p> 
                </div>
                <div class="email">
                  <img src="{% static 'images/icons/social_mail.png' %}" alt="">
                  <p>agenciachaco@elanelsys.com	</p>
                </div>
              </div>
            </li>

            <li class="footer__contactanos-item">
              <h5>Corrientes Capital</h5>
              <div class="info">
                <div class="tel">
                  <img src="{% static 'images/icons/social_tel.png' %}" alt="">
                  <p>3795 16-1905</p> 
                </div>
                <div class="email">
                  <img src="{% static 'images/icons/social_mail.png' %}" alt="">
                  <p>agenciacorrientes@elanelsys.com</p>
                </div>
              </div>
            </li>

            <li class="footer__contactanos-item">
              <h5>Saenz Peña, Chaco</h5>
              <div class="info">
                <div class="tel">
                  <img src="{% static 'images/icons/social_tel.png' %}" alt="">
                  <p>364 491-4025</p> 
                </div>
                <div class="email">
                  <img src="{% static 'images/icons/social_mail.png' %}" alt="">
                  <p>agenciasaenzpenia@elanelsys.com</p>
                </div>
              </div>
            </li>

            <li class="footer__contactanos-item">
              <h5>Posadas, Misiones</h5>
              <div class="info">
                <div class="tel">
                  <img src="{% static 'images/icons/social_tel.png' %}" alt="">
                  <p>3765 10-4719</p> 
                </div>
                <div class="email">
                  <img src="{% static 'images/icons/social_mail.png' %}" alt="">
                  <p>agenciaposadas@elanelsys.com</p>
                </div>
              </div>
            </li>

            <li class="footer__contactanos-item">
              <h5>Goya, Corrientes</h5>
              <div class="info">
                <div class="email">
                  <img src="{% static 'images/icons/social_mail.png' %}" alt="">
                  <p>agenciagoya@elanelsys.com	</p>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <div class="footer__logo">
            <img src="{% static 'images/icons/icono_arreglado_blanco.png' %}" alt="">
        </div>

</footer>

templates/mail.html
{% load static %}
<html>
    <body style="text-align: center; ">

        {% if target %}
            <h1 style="font-size: 30px;">{{target}}</h1>
        {% else %}
            <h1 style="font-size: 30px;">ENVIO DE CURRICULUM</h1>
        {% endif %}

        <h2><strong style="color: #027cf1;">La persona</strong>  <br>{{person}}</h2>
        
        {% if provincia %}
            <h2><strong style="color: #027cf1;">Es de:</strong>  <br>{{provincia}}</h2>
        {% else %}
            <h6></h6>
        {% endif %}
        
        <h2><strong style="color: #027cf1;">Su numero de telefono es:</strong> <br>{{num_tel}}</h2>
        <h2><strong style="color: #027cf1;">Su correo es:</strong> <br>{{correo}}</h2>
    </body>
</html>

templates/nav.html
{% load static %}
<header>
  <nav class="header__nav">
    <ol>
      <a class="logo_container" href="{% url 'index' %}">
        <img
          src="{% static 'images/icons/icono_header_blanco_arreglado.png' %}"
          alt=""
          class="logo"
        />
      </a>
      <label for="check">
        <input type="checkbox" id="check" />
        <span></span>
        <span></span>
        <span></span>
      </label>

      <div class="nav__items">
        <li class="items__menu">
          <a href="{% url 'market:categorias' %}">Categorias</a>
          <img
            src="{% static 'images/icons/icon_expand.png' %}"
            alt=""
          />
          <ul class="menu_categoria">
            <li>
              <a href="{% url 'market:motos' %}">Motos</a>
            </li>
            <li>
              <a href="{% url 'market:soluciones_dinerarias' %}"
                >Soluciones dinerias</a
              >
            </li>
            <li>
              <a href="{% url 'market:electrodomesticos' %}"
                >Electrodomesticos</a
              >
            </li>
            <li>
              <a href="{% url 'market:motos'%}?status=True">Usados</a>
            </li>
          </ul>
        </li>
        <li class ="items">
          <a href="{% url 'market:beneficios' %}">Beneficios para clientes</a>
        </li>
        <li class="items">
          <a href="{% url 'nosotros' %}">Sobre Nosotros</a>
        </li>
        <li class="items">
          <a href="{% url 'market:trabaja' %}">Trabaja con nosotros</a>
        </li>
        <li class="items">
          <a href="{% url 'contactanos' %}">Contactanos</a>
        </li>
      </div>
    </ol>
  </nav>
</header>
<div class="espace_header_categories"></div>

templates/pagenotfound.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/notFound.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/notFound.css' %}" />
    <title>Elanel Servicios y Soluciones</title>
    <link rel="shortcut icon" href="{% static 'images/fwd/icon_page4.png' %}">
</head>
<body>
    {% include 'nav.html' %}
    <main>
        <div class="text_error">
            <div class="container_text">
                <h1>¡Lo sentimos! <br> Ocurrió un error inesperado</h1>
                <h2>Al parecer la pagina que estas buscando no existe. Aun asi te invitamos que sigas navegando por nuestra pagina.</h2>
                <a class="button_redirect" href="{% url 'index' %}">
                    <img src="{% static 'images/icons/icon_back_index.png' %}" alt="">
                    <h4>Volver</h4>
                </a>
            </div>
        </div>
        <div class="image_error">
            <figure><img src="{% static 'images/notfound.png' %}" alt=""></figure>
        </div>
    </main>
    <script src="{% static 'js/header.js' %}"></script>
    <script src="{% static 'js/menu_hamburguer.js' %}"></script>
</body>
</html>

templates/privacidad.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}">
    <link rel="stylesheet" href="{% static 'css/privacidad.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}">
    <link rel="stylesheet" href="{% static 'css/media_querys/footer.css' %}">
    
    <title>Elanel Servicios y Soluciones</title>
    <link rel="shortcut icon" href="{% static 'images/fwd/icon_page4.png' %}">
</head>
<body>
    {% include 'nav.html' %}
    <div class="text_wrapper">
        <p class="text_main">En Elanel Servicios y Soluciones, entendemos que la privacidad de nuestros clientes es importante. Por esta razón, hemos establecido la siguiente política de privacidad para proteger su información personal.</p>
        <h3>Recopilación de información</h3>
        <p>Cuando utiliza nuestros servicios, podemos recopilar información personal, como su nombre, dirección, dirección de correo electrónico, número de teléfono y otra información relevante. También podemos recopilar información sobre sus transacciones con nosotros.</p>
        <h3>Uso de la información</h3>
        <p>La información que recopilamos se utiliza para brindarle nuestros servicios y para mejorarlos. También podemos utilizar la información para enviarle correos electrónicos y boletines informativos relacionados con nuestros servicios.</p>
        <h3>Divulgación de información</h3>
        <p>No compartimos su información personal con terceros, excepto cuando sea necesario para proporcionarle nuestros servicios. En algunos casos, podemos divulgar información personal si se nos requiere por ley.</p>
        <h3>Seguridad de la información</h3>
        <p>Tomamos medidas razonables para proteger la información personal que recopilamos de pérdida, mal uso y acceso no autorizado, divulgación, alteración y destrucción. Sin embargo, tenga en cuenta que ninguna medida de seguridad es 100% efectiva.</p>
        <h3>Cookies y tecnologías similares</h3>
        <p>Utilizamos cookies y tecnologías similares para mejorar nuestros servicios y brindar una experiencia personalizada. Estas tecnologías nos permiten recopilar información sobre su uso de nuestros servicios, como la página que visitó, el tiempo que pasó en ella y la ubicación geográfica de su dispositivo.</p>
        <h3>Cambios a esta política de privacidad</h3>
        <p>Podemos actualizar esta política de privacidad en cualquier momento. Si realizamos cambios significativos a la forma en que manejamos su información personal, le notificaremos por correo electrónico o mediante una publicación destacada en nuestro sitio web.</p>
        <h3>Preguntas y comentarios</h3>
        <p>Si tiene alguna pregunta o comentario sobre nuestra política de privacidad, no dude en comunicarse con nosotros a través de nuestro sitio web o por correo electrónico.</p>
    </div>

    {% include 'footer.html' %}
    
</body>
<script src="{% static 'js/header.js' %}"></script>
</html>

templates/sobre_nosotros.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sobre_nosotros.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/media_querys/sobre_nosotros.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/media_querys/nav_bar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/media_querys/footer.css' %}" />

    <title>Elanel Servicios y Soluciones</title>
    <link
      rel="shortcut icon"
      href="{% static 'images/fwd/icon_page4.png' %}"
    />
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="wrapper">
      <section class="one_section">
        <video src="{% static 'images/images_sobre_nosotros/video_elanel.mp4' %}"  type="video/mp4" autoplay muted loop preload="auto">
        </video>

        {% comment %} <figure>
          <img
            src="{% static 'images/images_sobre_nosotros/section_1.jpg' %}"
            alt=""
          />
        </figure> {% endcomment %}
        <h1>Quienes <strong>Somos</strong></h1>
        <p>
          Bienvenidos a Elanel, tu tienda en línea de confianza. Aquí encontrarás una amplia variedad de productos de alta calidad, desde motocicletas hasta electrodomésticos, y también ofrecemos ayuda dineraria y servicio técnico. Además, nuestros clientes disfrutan de beneficios exclusivos y ofertas especiales. <br><strong>¡Compra con confianza en Elanel!</strong>
        </p>
      </section>
      <section class="two_section">
        <p>
          Somos una Empresa que comercializa productos y servicios fundada en la
          provincia del chaco que presenta un sistema original, moderno y
          exitoso, brindamos atención personalizada e inmediatez a la demanda de
          nuestros clientes con alcance nacional
        </p>
        <br />
        <p>
          Nos caracteriza el compromiso y la pasión por el trabajo constante, el
          desarrollo humano y profesional de nuestros colaboradores, Una
          compañía sólida y competitiva que brinda el mejor servicio, con
          innovación y creatividad, a través de la excelencia.
        </p>
      </section>
      <section class="three_section">
        <div class="mision">
          <h3>MISION</h3>
          <p>
            Cumplir totalmente las necesidades de nuestros clientes a través de
            la excelencia en el servicio, el desarrollo profesional de nuestros
            colaboradores y el compromiso con nuestro país.
          </p>
        </div>
        <div class="vision">
          <h3>VISION</h3>
          <p>
            Nuestra visión es ser una empresa líder en la comercialización de
            productos y servicios logrando la satisfacción y excediendo las
            expectativas de los clientes. Creando una cultura con huella de
            liderazgo que nos permita ser percibidos como primera opción del
            mercado
          </p>
        </div>
      </section>
      <section class="four_section">
        <figure>
          <img
            src="{% static '/images/images_sobre_nosotros/section_4.jpg' %}"
            alt=""
          />
        </figure>
        <h3 class="title_valores">NUESTROS VALORES</h3>
        <div class="text_1">
          <p>
            Lideramos con el ejemplo de una empresa que crea emociones,
            transforma el sueño y enriquece la vida de las personas en todo el
            pais, por medio de la sabiduría y la pasión, dispuesta a
            proporcionar siempre nuevas emociones.
          </p>
          <ul>
            <li>Trabajo en equipo</li>
            <li>Innovación</li>
            <li>Integridad(Honestos y Rectos)</li>
            <li>
              Profesionalismo (luchar por la excelencia y la mejora continua)
            </li>
            <li>Calidez (en nuestras relaciones)</li>
            <li>Lealtad(leal a la empresa)</li>
          </ul>
        </div>
        <h3 class="title_estrategia">ESTRATEGIA</h3>
        <div class="text_2">
          <ul>
            <li>
              <strong>Crecer:</strong> A través de la expansión nacional con
              resultados sostenibles
            </li>
            <li>
              <strong>Ofrecer:</strong> A nuestros clientes una experiencia
              diferente, basada en Servicios, comunicación innovadora, con
              calidad y calidez.
            </li>
            <li>
              <strong>Crear:</strong> Relaciones amigables con nuestros clientes
              y la comunidad.
            </li>
            <li>
              <strong>Desarrollar:</strong> Procesos simples y eficientes.
            </li>
            <li>
              <strong>Promover:</strong> El desarrollo continuo de nuestros
              colaboradores. Fomentar un clima de alegría, participación y
              trabajo en equipo. Proveer las mejores herramientas para
              gestionar.
            </li>
          </ul>
        </div>
      </section>
    </div>

    {% include 'footer.html' %}


    <script src="{% static 'js/menu_hamburguer.js' %}"></script>
    <script src="{% static 'js/header.js' %}"></script>
  </body>
</html>